apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-vip-cloud-provider.name" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      {{- include "kube-vip-cloud-provider.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "kube-vip-cloud-provider.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - command:
            - /kube-vip-cloud-provider
            - --leader-elect-resource-name=kube-vip-cloud-controller
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          name: {{ include "kube-vip-cloud-provider.name" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: {{ include "kube-vip-cloud-provider.name" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | indent 8 }}
      {{- end }}

